name: Build and release

on:
    push:
        tags:
            - 'v*.*.*'
            - 'v*.*.*-rc.*'

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3.3.0
              with:
                  node-version: 17
                  cache: 'npm'

            - name: Install Node dependencies
              run: npm install

            - name: Build the plugin
              run: npm run build

            - name: Package the plugin
              run: ./node_modules/.bin/wp-scripts plugin-zip

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: ucsc-gutenberg-blocks.zip
                  generate_release_notes: true
